name: Deploy GbxExplorer

on:
  workflow_dispatch:
  
env:
  PROJECT_NAME: GbxExplorer

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.202
        
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools
      
    - name: Install macos (for some reason)
      run: dotnet workload install macos
      
    - name: Publish
      run: dotnet publish Tools/GbxExplorer/Server -c Release -p:RunAOTCompilation=true --nologo -o publish --self-contained
        
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build
        path: publish
        
  deploy:
    needs: build

    runs-on: ubuntu-latest
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: build
        path: ${{env.PROJECT_NAME}}
    
    - name: Deploy to Ubuntu using Rsync
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr
        path: ${{env.PROJECT_NAME}}/ # trailing slash means copy content
        remote_path: /var/www/${{env.PROJECT_NAME}}
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.KEY }}
        
    - name: Restart the application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: sudo systemctl restart ${{env.PROJECT_NAME}}
