name: Publish Pre-release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build

    if: "github.event.release.prerelease"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          7.0.202
          6.0.x
          3.1.x
          
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build
        path: Src/GBX.NET/bin/Release/GBX.NET.*.nupkg
  
  publish:    
    needs: build
    
    name: Publish
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: build
        
    - name: Publish the GBX.NET package to nuget.org
      run: dotnet nuget push GBX.NET.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
    
    - name: Publish the GBX.NET package to github.com
      run: dotnet nuget push GBX.NET.*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/bigbang1112/index.json
    
    - name: Upload the GBX.NET package to the release
      uses: svenstaro/upload-release-action@v2
      with:
        file: GBX.NET.*.nupkg
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
